import type { Capabilities, Case, Method, Result } from '../api/client'
import { CitationButton } from './CitationButton'
import { ExportMenu } from './ExportMenu'
import { GenerationControls } from './GenerationControls'
import { InlineNotice } from './InlineNotice'
import { RunProvenance } from './RunProvenance'
export function NotePane({result,consultation,method,visible,capabilities,busy,pending,error,onGenerate,onCitation}:{result:Result,consultation:Case,method:Method,visible:boolean,capabilities:Capabilities|null,busy:boolean,pending:boolean,error?:string,onGenerate:()=>void,onCitation:(id:string,button:HTMLButtonElement)=>void}){
  return <section className={'pane note-pane'+(visible?' selected-note':'')} aria-labelledby={'note-title-'+method} aria-busy={pending}><div className="pane-heading"><span className="eyebrow">Méthode {method==='direct'?'A':'B'}</span><h2 id={'note-title-'+method}>{method==='direct'?'Résumé direct':'Extraction structurée'}</h2><p>{method==='direct'?'Un appel IA → une note rédigée':'Un appel IA → faits → rendu Python'}</p></div><RunProvenance result={result}/><div className="note-controls"><GenerationControls capabilities={capabilities} busy={busy} pending={pending} onGenerate={onGenerate}/><ExportMenu result={result} consultation={consultation}/></div>{error&&<InlineNotice error>{error}</InlineNotice>}{pending&&<InlineNotice>L’exemple précédent reste affiché pendant la génération.</InlineNotice>}<div className="pane-content note-content">{result.note.sections.map(section=><section className="note-section" key={section.key}><h3>{section.title}</h3>{section.assertions.length?section.assertions.map(a=><div className="assertion" key={a.assertion_id}><p>{a.text}</p><div className="citations">{a.citations.map(c=><CitationButton citation={c} key={c.citation_id} onSelect={onCitation}/>)}{!a.citations.length&&<span className="quiet">Aucune citation fournie</span>}</div></div>):<p className="empty-section">Non mentionné</p>}</section>)}</div></section>
}
