/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Capabilities */
        get: operations["get_capabilities_api_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Examples */
        get: operations["list_examples_api_examples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/examples/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Example */
        get: operations["get_example_api_examples__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Note */
        post: operations["generate_note_api_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_api_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiError */
        ApiError: {
            error: components["schemas"]["ErrorDetail"];
            /** Request Id */
            request_id: string;
        };
        /** Capabilities */
        Capabilities: {
            /** Global Remaining */
            global_remaining: number;
            /** Live Available */
            live_available: boolean;
            /** Methods */
            methods: components["schemas"]["Method"][];
            /** Next Attempt At */
            next_attempt_at: string | null;
            /** Reason */
            reason: string | null;
            /** Visitor Remaining */
            visitor_remaining: number;
        };
        /** Citation */
        Citation: {
            /** Citation Id */
            citation_id: string;
            /** Quote */
            quote: string | null;
            /** Resolvable */
            resolvable: boolean;
            /** Segment Id */
            segment_id: string;
        };
        /** ClinicalNote */
        ClinicalNote: {
            /** Canonical Text */
            canonical_text: string;
            /** Case Id */
            case_id: string;
            /** Note Sha256 */
            note_sha256: string;
            /** Sections */
            sections: components["schemas"]["NoteSection"][];
        };
        /** ConsultationCase */
        ConsultationCase: {
            /** Case Id */
            case_id: string;
            /**
             * Family Id
             * @enum {string}
             */
            family_id: "respiratoire" | "cardiovasculaire" | "digestif" | "urinaire" | "musculosquelettique" | "neurologique" | "dermatologique" | "suivi-chronique" | "sante-psychique" | "prevention";
            /** Focus Tags */
            focus_tags: string[];
            /** Group Id */
            group_id: string;
            /**
             * Locale
             * @constant
             */
            locale: "fr-FR";
            /** Provenance Id */
            provenance_id: string;
            /**
             * Schema Version
             * @constant
             */
            schema_version: "1.0";
            /** Segments */
            segments: components["schemas"]["SourceSegment"][];
            /**
             * Split
             * @enum {string}
             */
            split: "dev" | "test" | "stress";
            stress_pair: components["schemas"]["StressPairMetadata"] | null;
            /**
             * Suite
             * @enum {string}
             */
            suite: "main" | "stress";
            /** Title */
            title: string;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Retry After Seconds */
            retry_after_seconds: number | null;
        };
        /** ExampleSummary */
        ExampleSummary: {
            /** Case Id */
            case_id: string;
            /** Focus */
            focus: string;
            /** Origins */
            origins: {
                [key: string]: "illustrative" | "llm_recorded" | "llm_live";
            };
            /** Title */
            title: string;
        };
        /** GenerateRequest */
        GenerateRequest: {
            /** Case Id */
            case_id: string;
            method: components["schemas"]["Method"];
        };
        /** GenerationResult */
        GenerationResult: {
            /** Case Id */
            case_id: string;
            checks: components["schemas"]["TechnicalChecks"];
            fidelity_metrics: components["schemas"]["NoteEvaluation"] | null;
            metadata: components["schemas"]["RunMetadata"];
            method: components["schemas"]["Method"];
            note: components["schemas"]["ClinicalNote"];
            /**
             * Origin
             * @enum {string}
             */
            origin: "illustrative" | "llm_recorded" | "llm_live";
            review: components["schemas"]["Review"];
            /** Run Id */
            run_id: string;
        };
        /**
         * Method
         * @enum {string}
         */
        Method: "direct" | "structured";
        /** MetricValue */
        MetricValue: {
            /** Denominator */
            denominator: number;
            /** Numerator */
            numerator: number;
            /** Value */
            value: number | null;
        };
        /** NoteAssertion */
        NoteAssertion: {
            /** Assertion Id */
            assertion_id: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Text */
            text: string;
        };
        /** NoteEvaluation */
        NoteEvaluation: {
            /** Annotation Sha256 */
            annotation_sha256: string;
            /** Metrics */
            metrics: {
                [key: string]: components["schemas"]["MetricValue"];
            };
            /** Note Sha256 */
            note_sha256: string;
        };
        /** NoteSection */
        NoteSection: {
            /** Assertions */
            assertions: components["schemas"]["NoteAssertion"][];
            key: components["schemas"]["SectionKey"];
            /** Title */
            title: string;
        };
        /** PairedComparison */
        PairedComparison: {
            /** A */
            a: number | null;
            /** B */
            b: number | null;
            /** Ci95 High */
            ci95_high: number | null;
            /** Ci95 Low */
            ci95_low: number | null;
            /** Difference */
            difference: number | null;
            /** N */
            n: number;
            /** Unit */
            unit: string;
            /** Warnings */
            warnings: string[];
        };
        /** PublicExample */
        PublicExample: {
            consultation: components["schemas"]["ConsultationCase"];
            /** Results */
            results: {
                [key: string]: components["schemas"]["GenerationResult"];
            };
        };
        /** PublishedMetrics */
        PublishedMetrics: {
            /** By Method */
            by_method: {
                [key: string]: {
                    [key: string]: components["schemas"]["MetricValue"];
                };
            };
            /** Comparisons */
            comparisons: {
                [key: string]: components["schemas"]["PairedComparison"];
            };
            /** Conditional By Method */
            conditional_by_method: {
                [key: string]: {
                    [key: string]: components["schemas"]["MetricValue"];
                };
            };
            /** Counts By Method */
            counts_by_method: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Failures */
            failures: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Stress */
            stress: {
                [key: string]: components["schemas"]["MetricValue"];
            };
        };
        /** PublishedReport */
        PublishedReport: {
            /** Artifact Links */
            artifact_links: {
                [key: string]: string;
            };
            /** Cohort Sizes */
            cohort_sizes: {
                [key: string]: number;
            };
            /** Hashes */
            hashes: {
                [key: string]: string;
            };
            /** Limitations */
            limitations: string[];
            metrics: components["schemas"]["PublishedMetrics"] | null;
            /** Review Status */
            review_status: {
                [key: string]: string;
            };
            /**
             * Schema Version
             * @constant
             */
            schema_version: "1.0";
            /**
             * Status
             * @enum {string}
             */
            status: "awaiting_runs" | "awaiting_annotation" | "awaiting_reference_review" | "ai_annotated" | "human_reviewed";
        };
        /** Review */
        Review: {
            /** Artifact Sha256 */
            artifact_sha256: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "none" | "ai" | "human";
            /** Reviewed At */
            reviewed_at: string | null;
            /** Reviewer Id */
            reviewer_id: string | null;
        };
        /** RunMetadata */
        RunMetadata: {
            /** Attempts */
            attempts: number;
            /** Corpus Sha256 */
            corpus_sha256: string;
            /** Created At */
            created_at: string;
            /** Duration Ms */
            duration_ms: number | null;
            /** Estimated Cost Usd */
            estimated_cost_usd: number | null;
            /** Input Tokens */
            input_tokens: number | null;
            /** Model Requested */
            model_requested: string | null;
            /** Model Returned */
            model_returned: string | null;
            /** Output Tokens */
            output_tokens: number | null;
            /** Prompt Sha256 */
            prompt_sha256: string;
            /** Prompt Version */
            prompt_version: string;
            /** Renderer Sha256 */
            renderer_sha256: string;
            /** Schema Sha256 */
            schema_sha256: string;
        };
        /**
         * SectionKey
         * @enum {string}
         */
        SectionKey: "reason" | "history" | "background" | "medications_allergies" | "observations" | "assessment" | "plan";
        /** SourceSegment */
        SourceSegment: {
            /** Segment Id */
            segment_id: string;
            /**
             * Speaker
             * @enum {string}
             */
            speaker: "patient" | "clinician" | "other";
            /** Text */
            text: string;
        };
        /** StressPairMetadata */
        StressPairMetadata: {
            /** Invariant Fact Keys */
            invariant_fact_keys: string[];
            /** Pair Id */
            pair_id: string;
            /** Target Fact Key */
            target_fact_key: string;
            /**
             * Variant
             * @enum {string}
             */
            variant: "positive" | "negative";
        };
        /** TechnicalChecks */
        TechnicalChecks: {
            /** Assertions Without Citation */
            assertions_without_citation: string[];
            /** References Emitted */
            references_emitted: number;
            /** References Resolvable */
            references_resolvable: number;
            /** Schema Valid */
            schema_valid: boolean;
            /** Unresolved Ids */
            unresolved_ids: string[];
            /** Warnings */
            warnings: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_capabilities_api_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capabilities"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_examples_api_examples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExampleSummary"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    get_example_api_examples__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicExample"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    generate_note_api_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationResult"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    live_api_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    get_report_api_report_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishedReport"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
