import { useEffect, useState } from 'react'
import type { Report } from '../api/client'
import type { DataProvider } from '../data/provider'
import { RecordedDataProvider } from '../data/recorded-provider'
import { formatMetric } from '../lib/formatters'
import { InlineNotice } from '../components/InlineNotice'
const labels:Record<Report['status'],string>={awaiting_runs:'Générations réelles en attente',awaiting_annotation:'Annotation des sorties en attente',awaiting_reference_review:'Revue humaine des références en attente',ai_annotated:'Évaluation exploratoire annotée par IA',human_reviewed:'Références et sorties revues humainement'}
export function ResultsPage({provider}:{provider:DataProvider}){
  const [report,setReport]=useState<Report|null>(null);const [error,setError]=useState('');const [local,setLocal]=useState(provider.offline)
  useEffect(()=>{let alive=true;async function load(){try{let r;try{r=await provider.getReport()}catch{r=await new RecordedDataProvider().getReport();if(alive)setLocal(true)}if(alive)setReport(r)}catch{if(alive)setError('Rapport indisponible.')}}void load();return()=>{alive=false}},[provider])
  return <article className="reading-page"><span className="eyebrow">Étude comparative</span><h1>Résultats & état de la revue</h1>{error&&<InlineNotice error>{error}</InlineNotice>}{local&&<InlineNotice>Rapport du bundle local.</InlineNotice>}{report?<><p className="report-status">{labels[report.status]}</p><p>La fidélité des notes doit être évaluée à partir de leurs sources et d’annotations complètes. Un résultat absent est affiché « Non évalué ».</p><div className="cohorts">{[['dev','Consultations de développement'],['test','Consultations test'],['stress_pairs','Paires de négation']].map(([key,label])=><div key={key}><strong>{report.cohort_sizes[key]}</strong><span>{label}</span></div>)}</div><h2>Comparaison des pipelines complets</h2><table><caption>Mesures calculées uniquement depuis les sorties et leurs annotations</caption><thead><tr><th>Mesure</th><th>A · Direct</th><th>B · Structuré</th><th>B − A / IC95</th></tr></thead><tbody>{['omission','coverage','unsupported','contradiction','citation_precision'].map(key=><tr key={key}><th>{({omission:'Omissions',coverage:'Couverture fidèle',unsupported:'Ajouts non soutenus',contradiction:'Contradictions',citation_precision:'Précision des citations'} as Record<string,string>)[key]}</th><td>{formatMetric(report.metrics?.by_method.direct?.[key]?.value)}</td><td>{formatMetric(report.metrics?.by_method.structured?.[key]?.value)}</td><td>{formatMetric(report.metrics?.comparisons[key]?.difference)}{report.metrics?.comparisons[key]?.ci95_low!=null&&<> · [{formatMetric(report.metrics.comparisons[key].ci95_low)} ; {formatMetric(report.metrics.comparisons[key].ci95_high)}]</>}</td></tr>)}</tbody></table><h2>Limites et provenance</h2><ul>{report.limitations.map(l=><li key={l}>{l}</li>)}</ul><p>La revue complète des références et des notes finales est nécessaire à l’étude finalisée. Aucun gain de performance n’est présupposé.</p><div className="artifact-links">{Object.entries(report.artifact_links).map(([label,url])=><a key={label} href={url}>{label==='protocol'?'Consulter le protocole':label}</a>)}</div></>:<p role="status">Chargement du rapport…</p>}</article>
}
